In [3]:
# 설치하기
!uv add numpy 

Resolved 34 packages in 1ms
Checked 33 packages in 2ms


In [4]:
import numpy as np

In [5]:
print(np.__version__)

2.5.1


In [6]:
!uv pip list | findstr numpy

numpy                   2.5.1


In [7]:
np.arange(10)  # ([start,] stop [,step])

# python을 이용한 계산
%time sum(range(1000000))

CPU times: total: 0 ns
Wall time: 8.38 ms


499999500000

In [8]:
np.arange(10)  # ([start,] stop [,step])
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: total: 0 ns
Wall time: 5.23 ms


np.int64(499999500000)

In [ ]:
import numpy as np

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3],[4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64

배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [11]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [12]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.])
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [ ]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # (3,)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [ ]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

In [14]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [15]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 즉 같은 데이터 타입만 저장 할 수 있다.
a = np.array([1, '2', 3])
print(a)             # ['1' '2' '3']

['1' '2' '3']


In [16]:
a = np.array(['a', 1, True])
print(a)              # array(['a', '1', 'True'], dtype='<U21')

['a' '1' 'True']


In [18]:
a = np.array([True, False, True])
print(a)               # array([ True, False,  True])

[ True False  True]


In [17]:
a = np.array([True, False, True, 0, 1]) # False -> 0, True -> 1
print(a)                 #  array([1, 0, 1, 0, 1])

[1 0 1 0 1]


In [19]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [20]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [22]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
a = np.eye(3, 2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [33]:
# 1를 시작되는 위치를 지정할 수 있다
a = np.eye(3, 4, k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
a = np.full((2,2),1)
print(a)

[[1 1]
 [1 1]]


In [28]:
a = np.full((2,2), [1, 2])
print(a)

[[1 2]
 [1 2]]


In [29]:
a = np.full((2,2), [[1],[2]])
print(a)

[[1 1]
 [2 2]]


In [30]:
a = np.full((2,2), [[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [34]:
a = np.empty(3)
print(a)

[1. 1. 1.]


In [35]:
a = np.empty((2,3))
print(a)

[[1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
# linspace(시작값, 끝값, 갯수 (default = 50))
a = np.linspace(0,49)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [ ]:
a = np.linspace(0,5)
print(a)

[0.  2.5 5. ]


In [40]:
a = np.linspace(0,5,endpoint=False)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


In [41]:
a = np.logspace(1,50)
print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20
 1.e+21 1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28 1.e+29 1.e+30
 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49 1.e+50]


In [43]:
a = np.logspace(1,50,10)
print(a)

[1.00000000e+01 2.78255940e+06 7.74263683e+11 2.15443469e+17
 5.99484250e+22 1.66810054e+28 4.64158883e+33 1.29154967e+39
 3.59381366e+44 1.00000000e+50]


In [44]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
arr = np.arange(3,10)
print(arr)

[3 4 5 6 7 8 9]


In [47]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [48]:
arr = np.arange(0,1,0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [50]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [51]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

# empty 메모리에 있는 값이나 이전에 사용했던 값들로 채워짐
b = np.empty_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [53]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [56]:
# 동일한 난수 결과 발생을 위한 난수 시드 값 고정
np.random.seed(42)

num = np.random.rand(2, 3)
print(num)

# 평균 0, 표준편차 1 구조를 만족하는 3행 3열의 정규분포 매트릭스 빌드
normal_dist_matrix = np.random.randn(3, 3)
print(normal_dist_matrix)   # [[-0.23415337 ... 0.24196227]]

# 1부터 45 미만의 범위에서 무작위 로또 번호 숫자를 닮은 6개 정수 생성
lotto_numbers = np.random.randint(1, 45, size=6)
print(lotto_numbers)     # [39 29 15 43  8 21]

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]
[42 28 16 15 44  3]


In [58]:
a = [1, 2, 3]        # list
b = a
print(b)
print(a is b )        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]           
print(b)                # [7, 2, 3]

[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


In [59]:
a = [1,2,3]
b = a.copy()
id(a)                 # 133162358434304
id(b)                 # 133162358425280
print(a is b)         # 주소 비교 False
print(a == b)         # 값 비교 True

b[0] = 8
# a는 안바뀐다.
print(a)               # [1, 2, 3]
print(b)               # [8, 2, 3]
print(a is b)          # 메모리 주소 비교  False
print(a == b)          # 값 비교           False

False
True
[1, 2, 3]
[8, 2, 3]
False
False


In [60]:
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 133162358428608
print(id(b))              # 133162358989568

print(a is b)             # False
print(a == b)             # True 

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
2163285343680
2163285338368
False
True
[10, 2, 3]
[10, 2, 3]


In [61]:
import copy

a = [[1,2,3]]
# list가 2차원일때 deep copy을 하기 위해서 copy모듈에 있는 
# deepcopy메소드를 사용한다.
b = copy.deepcopy(a) 

print(a[0] is b[0])        # 메모리 주소 False
print(a[0] == b[0])        # 값 True

b[0][0] = 10

print(a[0] is b[0])         # 메모리 주소 False
print(a[0] == b[0])         # 값 False

print(a)                    # [[1, 2, 3]]
print(b)                    # [[10, 2, 3]]

False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


In [62]:
a = [1,2,3]
b = a[:]
print(a)                      # [1,2,3]
print(b)                      # [1,2,3]

b[0] = 10
print(a)                      # [1, 2, 3]
print(b)                      # [10, 2, 3]

a = [[1,2,3]]
b = a[:]
print(a is b)                 # False
print(a == b)                 # True

 # 메모리 주소 비교  => 2차원일때 deepcopy 가 발생되지 않음
print(a[0][0] is b[0][0])                    #True
print(a[0][0] == b[0][0])  # 값비교           True

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[10, 2, 3]
False
True
True
True


In [63]:
# numpy에서 copy
a = b = np.array([1,2,3])
print(a is b)                         # True
print(a == b)                         # [ True  True  True]

a[0] = 100
print(a[0])                           # 100
print(b[0])                           # 100


a = np.array([1,2,3])
b = a.copy()

print(a is b)                           # 메모리 주소 False      
print(a == b)                           # 값 [ True  True  True]

True
[ True  True  True]
100
100
False
[ True  True  True]


In [65]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[bool_mask])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [77]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

axis_ABC = ['A', 'A', 'B', 'C', 'C']

bool_mask = arr[axis_ABC == 'A']
print(arr[bool_mask])  # 출력: [[0,1,2,3], [4,5,6,7]]

[]


In [74]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]]

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


In [78]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [85]:
type(...)

ellipsis

In [88]:
a[:, [1], :].shape

(2, 1, 4)

In [90]:
np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

In [89]:
# ... 양쪽으로 출력 갯수 지정
np.set_printoptions(edgeitems=6)

np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

In [92]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(arr is dap)
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')  

[1 2 3 4]
False
메모리 공유 확인:: False


In [ ]:
a = np.arange(24).reshape(2,3,4)

print(a)

print(a[0, :, 1])        # array([1, 5, 9])

print(a[[0],:, [1]])     # array([[1, 5, 9]])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [95]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

print(np.hsplit(x, 3))
print(np.hsplit(x, (2,4)))

print(np.split(x, 3, axis=1))
print(np.split(x, (2, 4), axis=1))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [101]:
import numpy as np

# 1. shape (3, 5) 크기의 2차원 배열 생성
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

# 2. 전치(Transpose) 및 축 교환(Swap Axes) 연산 (모두 동일한 결과 반환)
# ① .T 속성 사용
transposed_T = a.T

# ② np.transpose() 함수 사용
transposed_func = np.transpose(a)

# ③ np.swapaxes() 함수 사용 (0번 축과 1번 축을 맞바꿈)
swapped = np.swapaxes(a, 0, 1)

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(a)
# 원본 배열 출력 (shape: 3, 5):
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]

# ① a.T -> 전치 행렬
print(transposed_T)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ② np.transpose(a) -> 전치 행렬
print(transposed_func)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ③ np.swapaxes(a, 0, 1) -> 축 맞바꿈
print(swapped)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# Shape(모양) 확인 ( (3, 5) -> (5, 3)으로 변환 )
print(a.shape)            # 원본 크기 -> 출력: (3, 5)
print(transposed_T.shape) # 변환 후 크기 -> 출력: (5, 3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(3, 5)
(5, 3)
